export const nutritionDB = {
  "candy":                { calories: 450, protein: 0,   carbs: 90, fat: 5,   healthScore: 20 },
  "french fries":         { calories: 312, protein: 3.4, carbs: 41, fat: 15,  healthScore: 25 },
  "chocolate":            { calories: 546, protein: 4.2, carbs: 61, fat: 31,  healthScore: 15 },
  "biscuit":              { calories: 127, protein: 1.5, carbs: 20, fat: 4,   healthScore: 45 },
  "popcorn":              { calories: 387, protein: 12,  carbs: 78, fat: 4.5, healthScore: 55 },
  "ice cream":            { calories: 207, protein: 3.5, carbs: 24, fat: 11,  healthScore: 30 },
  "cheese butter":        { calories: 717, protein: 0.9, carbs: 0.1, fat: 81, healthScore: 10 },
  "cake":                 { calories: 380, protein: 4,   carbs: 55, fat: 16,  healthScore: 25 },
  "coffee":               { calories: 1,   protein: 0.1, carbs: 0,   fat: 0,   healthScore: 85 },
  "juice":                { calories: 45,  protein: 0.4, carbs: 11, fat: 0.1, healthScore: 65 },
  "milk":                 { calories: 42,  protein: 3.4, carbs: 5,   fat: 1,   healthScore: 80 },
  "almond":               { calories: 579, protein: 21,  carbs: 22, fat: 50,  healthScore: 70 },
  "red beans":            { calories: 132, protein: 8.7, carbs: 24, fat: 0.5, healthScore: 85 },
  "cashew":               { calories: 553, protein: 18,  carbs: 30, fat: 44,  healthScore: 65 },
  "dried cranberries":    { calories: 308, protein: 0.2, carbs: 82, fat: 1.4, healthScore: 50 },
  "walnut":               { calories: 654, protein: 15,  carbs: 14, fat: 65,  healthScore: 75 },
  "egg":                  { calories: 155, protein: 13,  carbs: 1.1, fat: 11,  healthScore: 85 },
  "apple":                { calories: 52,  protein: 0.3, carbs: 14, fat: 0.2, healthScore: 92 },
  "apricot":              { calories: 48,  protein: 1.4, carbs: 11, fat: 0.4, healthScore: 90 },
  "avocado":              { calories: 160, protein: 2,   carbs: 8.5, fat: 15,  healthScore: 88 },
  "banana":               { calories: 89,  protein: 1.1, carbs: 23, fat: 0.3, healthScore: 85 },
  "strawberry":           { calories: 32,  protein: 0.7, carbs: 7.7, fat: 0.3, healthScore: 95 },
  "cherry":               { calories: 50,  protein: 1,   carbs: 12, fat: 0.3, healthScore: 90 },
  "blueberry":            { calories: 57,  protein: 0.7, carbs: 14, fat: 0.3, healthScore: 94 },
  "raspberry":            { calories: 52,  protein: 1.2, carbs: 12, fat: 0.7, healthScore: 93 },
  "mango":                { calories: 60,  protein: 0.8, carbs: 15, fat: 0.4, healthScore: 88 },
  "olives":               { calories: 115, protein: 0.8, carbs: 6.3, fat: 11,  healthScore: 70 },
  "peach":                { calories: 39,  protein: 0.9, carbs: 10, fat: 0.3, healthScore: 89 },
  "lemon":                { calories: 29,  protein: 1.1, carbs: 9.3, fat: 0.3, healthScore: 92 },
  "pear":                 { calories: 57,  protein: 0.4, carbs: 15, fat: 0.1, healthScore: 90 },
  "fig":                  { calories: 74,  protein: 0.8, carbs: 19, fat: 0.3, healthScore: 87 },
  "pineapple":            { calories: 50,  protein: 0.5, carbs: 13, fat: 0.1, healthScore: 89 },
  "grape":                { calories: 69,  protein: 0.7, carbs: 18, fat: 0.2, healthScore: 86 },
  "kiwi":                 { calories: 61,  protein: 1.1, carbs: 15, fat: 0.5, healthScore: 92 },
  "melon":                { calories: 34,  protein: 0.8, carbs: 8,   fat: 0.2, healthScore: 90 },
  "orange":               { calories: 47,  protein: 0.9, carbs: 12, fat: 0.1, healthScore: 91 },
  "watermelon":           { calories: 30,  protein: 0.6, carbs: 8,   fat: 0.2, healthScore: 92 },
  "steak":                { calories: 271, protein: 25,  carbs: 0,   fat: 19,  healthScore: 55 },
  "chicken duck":         { calories: 172, protein: 25,  carbs: 0,   fat: 7.4, healthScore: 70 },
  "sausage":              { calories: 330, protein: 13,  carbs: 2,   fat: 30,  healthScore: 35 },
  "fried meat":           { calories: 350, protein: 20,  carbs: 5,   fat: 28,  healthScore: 40 },
  "lamb":                 { calories: 294, protein: 25,  carbs: 0,   fat: 21,  healthScore: 55 },
  "sauce":                { calories: 80,  protein: 1,   carbs: 5,   fat: 6,   healthScore: 40 },
  "fish":                 { calories: 206, protein: 22,  carbs: 0,   fat: 12,  healthScore: 85 },
  "soup":                 { calories: 40,  protein: 2,   carbs: 4,   fat: 1.5, healthScore: 75 },
  "bread":                { calories: 265, protein: 9,   carbs: 49, fat: 3.2, healthScore: 60 },
  "corn":                 { calories: 86,  protein: 3.2, carbs: 19, fat: 1.4, healthScore: 80 },
  "pizza":                { calories: 266, protein: 11,  carbs: 33, fat: 10,  healthScore: 45 },
  "pasta":                { calories: 131, protein: 5,   carbs: 25, fat: 1.1, healthScore: 65 },
  "rice":                 { calories: 130, protein: 2.7, carbs: 28, fat: 0.3, healthScore: 70 },
  "pie":                  { calories: 237, protein: 3,   carbs: 34, fat: 10,  healthScore: 40 },
  "eggplant":             { calories: 25,  protein: 1,   carbs: 6,   fat: 0.2, healthScore: 88 },
  "potato":               { calories: 77,  protein: 2,   carbs: 17, fat: 0.1, healthScore: 75 },
  "garlic":               { calories: 149, protein: 6.4, carbs: 33, fat: 0.5, healthScore: 85 },
  "tomato":               { calories: 18,  protein: 0.9, carbs: 3.9, fat: 0.2, healthScore: 94 },
  "spring onion":         { calories: 32,  protein: 1.8, carbs: 7.3, fat: 0.2, healthScore: 90 },
  "okra":                 { calories: 33,  protein: 2,   carbs: 7,   fat: 0.2, healthScore: 88 },
  "lettuce":              { calories: 15,  protein: 1.4, carbs: 2.9, fat: 0.2, healthScore: 96 },
  "cucumber":             { calories: 15,  protein: 0.7, carbs: 3.6, fat: 0.1, healthScore: 95 },
  "white radish":         { calories: 18,  protein: 0.6, carbs: 4.1, fat: 0.1, healthScore: 92 },
  "carrot":               { calories: 41,  protein: 0.9, carbs: 10,  fat: 0.2, healthScore: 91 },
  "broccoli":             { calories: 34,  protein: 2.8, carbs: 7,   fat: 0.4, healthScore: 96 },
  "snow peas":            { calories: 42,  protein: 2.8, carbs: 7.5, fat: 0.2, healthScore: 90 },
  "cabbage":              { calories: 25,  protein: 1.3, carbs: 5.8, fat: 0.1, healthScore: 92 },
  "bean sprouts":         { calories: 30,  protein: 3,   carbs: 5,   fat: 0.2, healthScore: 85 },
  "onion":                { calories: 40,  protein: 1.1, carbs: 9.3, fat: 0.1, healthScore: 85 },
  "pepper":               { calories: 31,  protein: 1,   carbs: 6,   fat: 0.3, healthScore: 90 },
  "green beans":          { calories: 31,  protein: 1.8, carbs: 7,   fat: 0.2, healthScore: 88 },
  "french beans":         { calories: 31,  protein: 1.8, carbs: 7,   fat: 0.2, healthScore: 88 },
  "king oyster mushroom": { calories: 37,  protein: 3,   carbs: 6,   fat: 0.5, healthScore: 85 },
  "shiitake":             { calories: 34,  protein: 2.2, carbs: 6.8, fat: 0.5, healthScore: 86 },
  "salad":                { calories: 20,  protein: 1,   carbs: 3,   fat: 0.5, healthScore: 90 },
  "other ingredients":    { calories: 150, protein: 5,   carbs: 15, fat: 8,   healthScore: 50 }
};

export function getNutritionForFood(foodName) {
  const key = foodName.toLowerCase();
  const nutrition = nutritionDB[key];
  if (nutrition) return nutrition;
  // fallback
  return { calories: 200, protein: 10, carbs: 20, fat: 8, healthScore: 65 };
}